name: Generate voice languages data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 06 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python 3.13
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Generate data
        env:
          GITHUB_GENERATOR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run generate:voice-languages

      - name: Upload data
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: voiceLanguages
          path: |
            ./_data/sttLanguages.json
            ./_data/ttsLanguages.json
          if-no-files-found: error
          retention-days: 1

  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    needs: generate
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download data
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: "voiceLanguages"
          path: "./_data/"

      - name: Create PR
        id: pr
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update voice languages data"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          sign-commits: true
          title: "Update voice languages data"
          body: |
            This PR was automatically generated by the workflow.
            It updates the voice languages data.
          base: main
          branch: update-voice-languages-data
          add-paths: |
            _data/ttsLanguages.json
            _data/sttLanguages.json