name: Generate voice languages data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 06 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Set up Python 3.13
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: Generate data
        env:
          GITHUB_GENERATOR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run generate:voice-languages

      - name: Upload data
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: voiceLanguages
          path: |
            ./_data/sttLanguages.json
            ./_data/ttsLanguages.json
          if-no-files-found: error
          retention-days: 1

  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    needs: generate
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Download data
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: "voiceLanguages"
          path: "./_data/"

      - name: Create PR
        id: pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update voice languages data"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          sign-commits: true
          title: "Update voice languages data"
          body: |
            This PR was automatically generated by the workflow.
            It updates the voice languages data.
          base: main
          branch: update-voice-languages-data
          add-paths: |
            _data/ttsLanguages.json
            _data/sttLanguages.json